# -*- mode: makefile -*-

# to build and install (locally) for all supported architectures just execute:
#  make -f Makefile.suggested -j16 build_all
#  (2:30 on rmc-uranos, 192MB binaries)
#
# to configure/build/install only a single architecture execute:
#  make -f Makefile.suggested ARCH=sled11-x86-gcc4.x configure build install

# settings:
SUPPORTED_ARCHS=sled11-x86-gcc4.x \
				sled11-x86_64-gcc4.x \
				vxworks6.7-x86-gcc4.x \
				vxworks6.8-x86-gcc4.x \
				vxworks6.9-x86-gcc4.x \
				vxworks6.9.3-x86-gcc4.x \
				vxworks6.9.4-x86-gcc4.x

ARGS=
#ARGS=--with-debug 

# architecture specific settings
ifeq ($(ARCH),sled11-x86-gcc4.x)
ARGS+=--disable-dependency-tracking # when configure just exits with 1
endif

ifeq ($(ARCH),sled11-x86_64-gcc4.x)
ifneq ($(shell uname -m),x86_64)
SSH=ssh rmc-thalia
endif
ARGS+=--disable-dependency-tracking # when configure just exits with 1
endif

ifeq ($(ARCH),arm-angstrom-linux-gnueabi)
OECORE_ROOT=/home/schm_fl/data/local/oecore-i686
HOST_OPTION="--host=arm-angstrom-linux-gnueabi"
TOOLCHAIN=${OECORE_ROOT}/sysroots/i686-angstromsdk-linux/usr/bin/armv7a-vfp-neon-angstrom-linux-gnueabi/
SOURCE_ENV="source $(OECORE_ROOT)/environment-setup-armv7a-vfp-neon-angstrom-linux-gnueabi"
ARGS+=--disable-dependency-tracking # when configure just exits with 1
endif

ifeq ($(findstring vxworks,$(ARCH)),vxworks)
TOOLCHAIN=/opt/vxworks/wrapper/linux/bin_configure/
HOST_OPTION="--host=$(shell ./scripts/arch_from_dlrrm $(ARCH))"
ARGS+=--disable-dependency-tracking PKG_CONFIG=/bin/false # when configure just exits with 1
PATH:=$(TOOLCHAIN):$(PATH)
endif

ifeq ($(ARCH),qnx6.3-x86-gcc3.3)
SOURCE_ENV="source /opt/qnx/run_qde_fixes.sh"
CXX="/opt/qnx/host/linux/x86/usr/bin/QCC -V 3.3.5,gcc_ntox86_cpp -fmessage-length=0"
CC="/opt/qnx/host/linux/x86/usr/bin/QCC -V 3.3.5,gcc_ntox86_cpp -fmessage-length=0"
ARGS+=--disable-dependency-tracking # when configure just exits with 1
HOST_OPTION=--host=$(shell ./scripts/arch_from_dlrrm $(ARCH)) CC=$(CC) CXX=$(CXX)
endif

ifeq ($(ARCH),qnx6.5-x86-gcc4.x)
SOURCE_ENV="source /volume/qnx/i686Linux/qcc-environment.sh qnx65"
CXX="/volume/qnx/i386Linux/qnx650/host/linux/x86/usr/bin/QCC -fmessage-length=0"
CC="/volume/qnx/i386Linux/qnx650/host/linux/x86/usr/bin/qcc -fmessage-length=0" 
ARGS+=--disable-dependency-tracking # when configure just exits with 1
HOST_OPTION=--host=$(shell ./scripts/arch_from_dlrrm $(ARCH)) CC=$(CC) CXX=$(CXX)
endif

SRC_DIR=$(CURDIR)
DST_DIR=$(SRC_DIR)/build/$(ARCH)

# targets
.PHONY: configure build install build_all $(SUPPORTED_ARCHS)

build_all: $(SUPPORTED_ARCHS)

$(SUPPORTED_ARCHS):
	make ARCH=$@ -f Makefile.suggested configure build install

configure:
ifeq ($(SSH),)
	mkdir -p $(DST_DIR)
	cd $(DST_DIR); $(SRC_DIR)/configure \
		--build `$(SRC_DIR)/config.guess` \
		$(HOST_OPTION) \
		TOOLCHAIN=$(TOOLCHAIN) \
		SOURCE_ENV=$(SOURCE_ENV) \
		DLRRM_ARCH=$(ARCH) \
		$(ARGS) \
		--prefix=$(DST_DIR)/install 
else
	$(SSH) make -C $(SRC_DIR) -f Makefile.suggested ARCH=$(ARCH) configure
endif

build:
	$(SSH) make -C $(DST_DIR)

install: build
	$(SSH) make -C $(DST_DIR) install

